### ISSUE TITLE
truffle-default-builder can't install 

### ISSUE THREAD

**Issue by chandrashekhar729** [rajivjc/mortgage-blockchain-demo#4]
Hello rajivjs,

PS E:\AppDevelopment\blockchain\mortgage-blockchain-demo> truffle serve
Serving static assets in .\build on port 8080...
Rebuilding...

C:\Users\Myriad-user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\chokidar\lib\fsevents-handler.js:26
  return (new fsevents(path)).on('fsevent', callback).start();
^
TypeError: fsevents is not a constructor
    at createFSEventsInstance (C:\Users\Myriad-user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\chokidar\lib\fsevents-handler.js:26:1)
    at setFSEventsListener (C:\Users\Myriad-user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\chokidar\lib\fsevents-handler.js:80:1)
    at FSWatcher.FsEventsHandler._watchWithFsEvents (C:\Users\Myriad-user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\chokidar\lib\fsevents-handler.js:244:1)
    at FSWatcher.<anonymous> (C:\Users\Myriad-user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\chokidar\lib\fsevents-handler.js:378:1)
    at LOOP (fs.js:1717:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by ylcnky** [comment]
Check [this issue](https://github.com/trufflesuite/truffle/issues/734)
@jiangcare's solution worked for me
